<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AForge" Version="2.2.5" NoWarn="NU1701" />
    <PackageReference Include="AForge.Video" Version="2.2.5" NoWarn="NU1701" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" NoWarn="NU1701" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
  </ItemGroup>

</Project>